### ISSUE TITLE
US0005

### ISSUE THREAD

**Issue by albaqueroh** [albaqueroh/be_java_hisp_w28_g08#6]

**Comment by Nico258** [comment]
## Dar de alta una nueva publicación.
		
### Sign:		
Method | SIGN
-- | --
POST | /products/post
PAYLOAD: | { "user_id": 123, "date": "29-04-2021", "product": {  									"product_id": 1, "product_name": "Silla Gamer", "type": "Gamer", "brand": "Racer", "color": "Red & Black", "notes": "Special Edition"  									}, "category": 100, "price": 1500.50  									}
RESPONSE | Status Code 200 (todo OK) Status Code 400 (Bad Request)


### Filtros/Parámetros:		
Parámetros | Tipo | Descripción/Ejemplo
-- | -- | --
user_id | int | Número que identifica a cada usuario
date | LocalDate | Fecha de la publicación en formato dd-MM-yyyy
product_id | int | Número identificatorio de un producto asociado a una publicación
product_name | String | Cadena de caracteres que representa el nombre de un producto
type | String | Cadena de caracteres que representa el tipo de un producto
brand | String | Cadena de caracteres que representa la marca de un producto
color | String | Cadena de caracteres que representa el color de un producto
notes | String | Cadena de caracteres para colocar notas u observaciones de un producto
category | int | Identificador que sirve para conocer la categoría a la que pertenece un producto. Por ejemplo: 100: Sillas, 58: Teclados
price | double | Precio del producto
